# Declare ignored files that should be included in deployment:
assets = [
    ".env", # include file.txt
    "frontend/dist/*", # include all files and subdirs in frontend/dist/
    "static/*", # include all files and subdirs in static/
]
